---
title: "NOAADashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(dplyr)
library(p8105.datasets)
library(plotly)
```

```{r}
data ("ny_noaa")

ny_noaa_tidy =
  rnoaa::meteo_pull_monitors(
    c ("USW00094728","USC00519397","USS0023B17S"),
    var = c ("PRCP", "TMIN", "TMAX"), 
    date_min ="2017-01-01",
    date_max = "2017-12-31")%>%
  mutate (
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY",
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"), 
    tmin = tmin/10,
    tmax = tmax/10) %>%
  select (name,id, date, prcp, tmin, tmax)%>%
  drop_na(tmax, tmin, prcp)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
ny_noaa_tidy %>%
  mutate (text_label = str_c("Date: ", date))%>%
  plot_ly(
    x= ~tmin, y = ~tmax, color = ~name,
    type = "scatter", mode = "markers", text = ~text_label
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa_tidy%>%
  plot_ly(
    y = ~tmax, color = ~name,
    type = "box"
  )
```

### Chart C

```{r}
ny_noaa_tidy%>%
  count(name)%>%
  plot_ly(
    x = ~name, y= ~n, 
    type = "bar")
```

